kind: pipeline
name: fluentd-test-arm64-3-0

platform:
  os: linux
  arch: arm64

steps:
- name: fluentd-test-arm64-3-0
  image: arm64v8/ruby:3.0
  commands:
  - apt update
  - apt -y install libgmp3-dev
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - gem update --system
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake test
---
kind: pipeline
name: fluentd-test-arm64-2-7

platform:
  os: linux
  arch: arm64

steps:
- name: fluentd-test-arm64-2-7
  image: arm64v8/ruby:2.7
  commands:
  - apt update
  - apt -y install libgmp3-dev
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - gem update --system
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake test
